#!/bin/bash

set -e

# This file is mostly a reference
# However, it is executable to quickly check that all boards still compile

make tada68:pwxn:bin
make 40percentclub/foobarMacro:default
make 40percentclub/foobarMacro:diablo
make 40percentclub/gherkin:ePipes

make paulKeyboard:default

make playkbtw/ca66:pwxn
